sbomType: Product SBOM
include:
  - path: Library/Device/
  - path: Library/NuMaker/
  - path: Library/PowerDeliveryLib/
  - path: Library/StdDriver/
  - path: Library/TKLib/
  - path: Library/UsbHostLib/
exclude:
  - path: Document/
  - path: Library/CMSIS/
  - path: SampleCode/
  - path: ThirdParty/
  - path: Tool/